# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- task: Go@0
  inputs:
    command: 'custom'
    customCommand: 'version'
  displayName: 'Get go version...'

- task: Go@0
  inputs:
    command: 'get'
    arguments: '-v -t -d ./...'
    workingDirectory: '$(modulePath)'
  displayName: 'Get deps...'

- task: Go@0
  inputs:
   command: 'build'
   arguments: '-v .'
   workingDirectory: '$(modulePath)'
  displayName: 'Build'
  env:
    CGO_ENABLED: 0 
    GOARCH: amd64 
    GOOS: linux

